### ISSUE TITLE
Error, the script can't be found

### ISSUE THREAD

**Issue by kruben95** [adnanh/webhook#179]
Hi, I started testing your webhook container and tried to test it with a simple `echo "test"` in the script.
The script is in place, the volume right and I can start the script manually with no problems
![webhook](https://user-images.githubusercontent.com/7986953/30823520-b8d48f62-a22c-11e7-8d1a-8a73f00a9c64.PNG)
(unless it doesn't require to write something like `echo "test" >> test.txt`, but that is another problem).

But when I try to trigger the script over the URL the log (I use portainer for console and log) says the following:

```
 [webhook] 2017/09/25 17:35:30 incoming HTTP request from 172.18.0.1:42760
 [webhook] 2017/09/25 17:35:30 testWebhook got matched
 [webhook] 2017/09/25 17:35:30 testWebhook hook triggered successfully
 [webhook] 2017/09/25 17:35:30 2017-09-25T17:35:30Z | 200 | 	 76.7µs | localhost:9001 | GET /hooks/testWebhook 
 [webhook] 2017/09/25 17:35:30 executing /var/webhook/scripts/testScript.sh (/var/webhook/scripts/testScript.sh) with arguments ["/var/webhook/scripts/testScript.sh"] and environment [] using /var/webhook/scripts/ as cwd
 [webhook] 2017/09/25 17:35:30 command output: 
 [webhook] 2017/09/25 17:35:30 error occurred: fork/exec /var/webhook/scripts/testScript.sh: no such file or directory
 [webhook] 2017/09/25 17:35:30 finished handling testWebhook
```

My script: 
```batch
 #!/bin/sh
 echo "test"
```

My webhooks.json:
```json
 [
   {
     "id": "testWebhook",
     "execute-command": "/var/webhook/scripts/testScript.sh",
     "command-working-directory": "/var/webhook/scripts/"
   }
 ]
```

My docker-compose.yml:
```yml
 webhook:
       container_name: webhook
       image: almir/webhook
       ports:
         - "9001:9000"
       expose:
         - "9001"
       volumes:
         - "./../webhook:/var/webhook"
       command: ["-verbose", "-hooks=/var/webhook/webhooks.json", "-hotreload"]
```

I have no idea where the problem is. The webhook.json is very similar to your example and the script is in the correct location. He finds the webhook.json in the correct directory, but why not the script that is one directory deeper in `/scripts`? The path is absolute so there shouldn't be any problems. Would be cool if you can help.
