### ISSUE TITLE
bitbucket - trigger on push on a particular branch ? (question)

### ISSUE THREAD

**Issue by Kitcat711** [adnanh/webhook#428]
Hello,
Thank you for this webhook, I appreciate it for my first node.js project.
I wonder if there is a way to trigger only when a push is on a particular branch.
I watched the payload of bitbucket - that I am using - and we can get the information, but was unable to trigger when branch = "master" only.
Is that possible?

Thank you for your answer.
Kitcat711

**Comment by moorereason** [comment]
Yes, it should be possible.  What trigger rules are you currently using?  If you're trying to react to [this payload](https://confluence.atlassian.com/bitbucket/event-payloads-740262817.html#EventPayloads-Push), I think you want to look for `push.changes.0.new.name` as the branch name.

**Comment by Kitcat711** [comment]
Thank you: worked perfectly. (I was missing the ".0." in my previous attempts).

**Comment by micahlagrange** [comment]
Please, tell me if this is what you used:

```yaml
value: "refs/heads/feature/whatever"
  parameter:
    source: payload
    name: push.changes.0.new.name
```
