### ISSUE TITLE
kubernetes + webhook + hotreload + error locating command

### ISSUE THREAD

**Issue by davidroman0O** [adnanh/webhook#456]
Hi everyone!

I found a weird behavior that should works (at least it's working docker-compose and volumes) with kubernetes!

I'm trying to have pods with webhook and be able to hot-reload the hooks and scripts. 😄 

With docker-compose and volumes, it's working but now I want to step up a little bit with kubernetes!

In this issue, normally you'll have everything to reproduce it on a k8s cluster!

So I got a simple setup with this manifest:

Manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a-webhook
  template:
    metadata:
      labels:
        app: a-webhook
    spec:  
      containers:
      - name: webhook-development
        imagePullPolicy: Always
        image: dalongrong/almir-webhook-curl
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: s-webhook-development
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: a-webhook

```

And then, I copy scripts and hooks.yaml with kubectl 

You'll need the podname sooo:

`kubectl get pods -l app=a-webhook -o json | jq -r '.items[].metadata.name'`

With the name, you can replace "podname" with the correct name.

Copy the scripts to the pod: 

`kubectl cp ./scripts podname:/var/ podname`

Copy the hooks to the pod:

`kubectl cp ./hooks.yaml podname:/etc/webhook podname`

hooks.yaml

```yaml
-   id: ping
    execute-command: /var/scripts/ping.sh
    command-working-directory: ./
    response-message: pong
```

scripts/ping.sh

```bash
#!/bin/sh
echo "pong"
```

After you executed the two commands, you should have this:

```shell
[webhook] 2020/09/15 16:56:59 caught HUP signal
[webhook] 2020/09/15 16:56:59 attempting to reload hooks from /etc/webhook/hooks.yaml
[webhook] 2020/09/15 16:56:59 found 1 hook(s) in file
[webhook] 2020/09/15 16:56:59 	loaded: ping
```

So, normally it should mean the hook is hot-reloaded and the scripts are located at `/var/scripts` 

If you bash in the pod, you can see the scripts!

And then, you can try to trigger the webhook but first you need to expose the port:

```bash
kubectl port-forward service/s-webhook-development 9000:9000 
```

And then on your browser to make it simply, go to : `http://localhost:9000/hooks/ping` 

You should see "pong" BUT on the logs :

```shell
[webhook] 2020/09/15 17:09:21 [c8acb1] incoming HTTP GET request from 127.0.0.1:60918
[webhook] 2020/09/15 17:09:21 [c8acb1] ping got matched
[webhook] 2020/09/15 17:09:21 [c8acb1] error parsing body payload due to unsupported content type header: 
[webhook] 2020/09/15 17:09:21 [c8acb1] ping hook triggered successfully
[webhook] 2020/09/15 17:09:21 [c8acb1] 200 | 4 B | 68.101µs | localhost:9000 | GET /hooks/ping
[webhook] 2020/09/15 17:09:21 [c8acb1] error locating command: '/var/scripts/ping.sh'
```

Thanks you for this amazing tool, can't wait to resolve this, I'm having a lot of fun! 

I hope I didn't forgot something, normally it should work on your side! 

Hope someone could help on this 😃
