### ISSUE TITLE
Bug when matching single payload 'match'

### ISSUE THREAD

**Issue by sokoow** [adnanh/webhook#519]
Hiya, nice engine, I'm about to start using it and I love the simplicity. Hey, I found a one strange thing in rule behaviour - I can't get a single match clause on payload value to work, here's what works:

payload:
```
{
  test-field: test,
  test-field2: test2
}
```

rule:
```
  trigger-rule:
  and:
    - match:
        type: value
        value: test
        parameter:
          source: payload
          name: test-field
    - match:
        type: value
        value: test2
        parameter:
          source: payload
          name: test-field2
```

here's what doesn't work:
payload:
```
{
  test-field: test,
  test-field2: test2
}
```

rule
```
  trigger-rule:
    match:
        type: value
        value: test
        parameter:
          source: payload
          name: test-field
```

rules get parsed and accepted ok for me, and logical and with 2 of them are ok, but a single match doesn't seem to work - see if you had any idea what's that about pls. greetings
