### ISSUE TITLE
Combine multiple JSON parameters to one argument?

### ISSUE THREAD

**Issue by NekoYos** [adnanh/webhook#601]
How to combine multiple JSON parameters to one argument?

I'm sent POST JSON data from prometheus with this structure:
```
{
  "version": "4",
  "groupKey": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string),              // key identifying the group of alerts (e.g. to deduplicate)
  "truncatedAlerts": [<int>](https://prometheus.io/docs/alerting/latest/configuration/#int),          // how many alerts have been truncated due to "max_alerts"
  "status": "<resolved|firing>",
  "receiver": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string),
  "groupLabels": <object>,
  "commonLabels": <object>,
  "commonAnnotations": <object>,
  "externalURL": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string),           // backlink to the Alertmanager.
  "alerts": [
    {
      "status": "<resolved|firing>",
      "labels": <object>,
      "annotations": <object>,
      "startsAt": "<rfc3339>",
      "endsAt": "<rfc3339>",
      "generatorURL": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string),      // identifies the entity that caused the alert
      "fingerprint": [<string>](https://prometheus.io/docs/alerting/latest/configuration/#string)        // fingerprint to identify the alert
    },
    ...
  ]
}
```

Parse payload to script args:
```
  pass-arguments-to-command:
  - source: url
    name: url
  - source: url
    name: room
  - source: url
    name: token
  - source: payload
    name: alerts.0.annotations.summary
```

We need combine all parameters from:
alerts.**0**.annotations.summary
alerts.**1**.annotations.summary
alerts.**2**.annotations.summary
alerts.**last**.annotations.summary
to one args
