### ISSUE TITLE
arguments with special characters.

### ISSUE THREAD

**Issue by foxsam21** [adnanh/webhook#622]
I would like to call a command that has the `&` character and also I need an argument with `"` in it. It seems that anything I tried is not working. In bash I can just call the whole thing in `"` and it works. I am trying to download a snapshot from an IP camera. Here is what I have (I use my actual user and camera IP in the real file):

```
- id: snapshot
  execute-command: "wget"
  command-working-directory: ""
  pass-arguments-to-command:
    - source: string
      name: "http://CAM/cgi-bin/api.cgi?cmd=Snap&channel=0&user=my_user"
    - source: string
      name: -O "/home/my_user/Desktop/snapshot $(date).jpg"

```
