### ISSUE TITLE
Using ~ and $HOME in config file is not supported

### ISSUE THREAD

**Issue by codedust** [adnanh/webhook#634]
Using `~` and `$HOME` are currently not supported in the config file. E.g.:

```yaml
- id: redeploy-webhook
  execute-command: "~/webhooks/hook.sh
  command-working-directory: "~/webhooks/"
```

Using `~` in `execute-command` results in this error message:
```
[webhook] 2023/04/29 12:17:06 [bd4e28] error in exec: "/home/user/webhooks/~/webhooks/hook.sh": stat /home/user/webhooks/~/webhooks/hook.sh: no such file or directory
```

Using `~` in `command-working-directory` results in this error message:
```
[webhook] 2023/04/29 12:18:24 [4a1bf6] error occurred: chdir ~/webhooks/: no such file or directory
```

Likewise, `$HOME` does not get interpreted.

Is there any specific reason why this is not possible or is it just not implemented?
