### ISSUE TITLE
I found that I can't use dot-notation to contain all sub-objects in my json

### ISSUE THREAD

**Issue by 1-step** [adnanh/webhook#663]
I've made a test.
the hook config file:
```
- id: playbook
  execute-command: "/root/webhook/replay2.sh"
  command-working-directory: "/root/webhook"
  pass-arguments-to-command:
    - source: "payload"
      name: "alerts.0.labels.instance"
    - source: "payload"
      name: "alerts.1.labels.instance"
```
is there any way so that i can use one command such as **"alerts.[].labels.instance"** to contain all sub-objects in my json.
