### ISSUE TITLE
Is it possible to use github webhooks whitelist IP in this way?

### ISSUE THREAD

**Issue by QooGeek** [adnanh/webhook#708]
```
- id: xxxx
  execute-command: "xxx"
  command-working-directory: "xxxxxxxx"
  response-message: Executing deploy script
  trigger-rule:
    and:
    - match:
        type: ip-whitelist
        ip-range: readFile "github_webhooks_ip_list.txt"
    - match:
        type: payload-hmac-sha1
        secret: xxxxxxxx
        parameter:
          source: header
          name: X-Hub-Signature
    - match:
        type: value
        value: refs/heads/xxxxx
        parameter:
          source: payload
          name: ref
```
          
github_webhooks_ip_list.txt

```
192.30.252.0/22
185.199.108.0/22
140.82.112.0/20
143.55.64.0/20
2a0a:a440::/29
2606:50c0::/32     
```
