### ISSUE TITLE
Script inside the script that webhook runs is not found

### ISSUE THREAD

**Issue by Ahydul** [adnanh/webhook#715]
This is using a docker container. In the logs I get: /scripts/test.sh: line 14: ./test2.sh: not found 

The script being run is this one:
```bash
#!/bin/sh

cd "$(dirname "$0")"
echo "After changing directory: $(pwd)"

echo "Listing contents of /scripts directory:"
ls -l /scripts

echo "Listing contents of . directory:"
ls -l .

#./send_ntfy_msg.sh 'test'

./test2.sh
```
test2.sh is:
```bash
#!/bin/bash
echo "test"
```

The scripts exist, are not owned by root and are executable (It works outside docker).
I've also tried an absolute path /scripts/test2.sh but it says: /scripts/test.sh: line 14: /scripts/test2.sh: not found
I'm really lost.

The hook is:

```yaml
- id: redeploy-webhook
  execute-command: "/scripts/test.sh"
 # command-working-directory: "/scripts"
  include-command-output-in-response: True
  http-methods: ["POST"]
  response-message: "Executing redeploy script"
  trigger-rule:
    match:
      type: value
      value: token #fake token
      parameter:
        source: header
        name: Authorization
```

And my compose file is:

```yaml
services:
  webhook:
    image: thecatlady/webhook
    container_name: webhook
    env_file: .env
    command: -verbose -hooks=./hooks.yaml -hotreload
    environment:
      - TZ=$TZ
    volumes:
      - ./config:/config:ro
      - /path/to/scripts:/scripts:ro #This is a fake path
    ports:
      - 9000:9000
    restart: always
```
